### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by chrisharrison** [nghialv/Net#21]
Swift 1.2 breaks this library.

**Comment by Jauzee** [comment]
@chrisharrison U just need to delete exclamation marks from functions parameters. :) I update Net.swift for Swift 1.2 through Xcode automatic error fix.

**Comment by Jauzee** [comment]
But on 
    '''class func apply(queueType: QueueType, interators: UInt, closure: GCDApplyClosure) {
        dispatch_apply(interators, queueType.getQueue(), closure)
    }'''

Xcode says: "Cannot invoke 'dispatch_apply' with an argument list of type '(UInt, dispatch_queue_t, GCDApplyClosure)'"

**Comment by chrisharrison** [comment]
@Jauzee Regarding your edit: yes, that's why I opened this. I haven't got time to convert at the moment. I think the Xcode 6.3 auto converter doesn't really work yet.

**Comment by yousies** [comment]
Any news on fixes yet...?

**Comment by danieldluyz** [comment]
Hello, does anybody know how to solve this?

**Comment by nghialv** [comment]
ok. This will be fixed at this weekend.

**Comment by danieldluyz** [comment]
I am using this library for something I have to deliver in 4 hours. Do you have any quick thoughts as to how I can fix it myself? Thanks!!

**Comment by nghialv** [comment]
I have just fixed this problem.

**Comment by cloudjanak** [comment]
Hi can anyone send me updated project for swift 2.0 
cloudjanak@gmail.com
